### ISSUE TITLE
Schematic + Board review

### ISSUE THREAD

**Issue by beeedy** [TDHolmes/BinaryClock_PCBFiles#1]
- possibly consider changing C3 - C6 to be decade increments instead of all the same value. If these are decoupling caps for more than just the USB to Serial converter ignore

- P1, not familiar with the connector but consider grounding the shield

- Don't know much about your architecture but you have U1 VCCIO set to 3.3V and your mico powered from 5V

- R1 and R2 seem a little high for current limiting, may want to double check these values

- I really hate to recommend a design change, but it might be worth looking into switching to high side switches rather than discrete P-FETs. Something like a tps27081 or TPS27082 might be something to look into

- +5V power line seems a little on the small side, could possibly beef it up in some spots but not critical

- Front silkscreen has some overlapping labels

- There is silkscreen on the back, although I am assuming you are just not sending out the back silk gerber

**Comment by TDHolmes** [comment]
- Agreed, should have done that.
- You should only ground a shield on one side of the cable. I assume the USB host is grounding the shield
- I double checked and this is the recommended layout for interfacing with boards. I'm assuming it's powering it's own internal circuitry. (http://www.ftdichip.com/Support/Documents/DataSheets/ICs/DS_FT230X.pdf page 23)
- I agree. This was a last minute decision to add debugging capabilities but the LEDs were too small to properly attach to the board anyways. Going to use 0805 LEDs or larger from now on!
- This would be an issue if I was multiplexing slowly. When I don't update the LEDs quickly, I get bleed over on the active row, but since I change active rows so quickly, it isn't visible. So not worth the increased cost.
- Will address in later board revisions.
- Fixed.
- Correct.
